### ISSUE TITLE
how to get shopify http response header using shopify-php-sdk?

### ISSUE THREAD

**Issue by lyongdee** [robwittman/shopify-php-sdk#17]
how to get shopify http response header using shopify-php-sdk?

**Comment by lyongdee** [comment]
@robwittman I want to control  [API limit call](https://help.shopify.com/api/getting-started/api-call-limit), how to do it.

**Comment by robwittman** [comment]
After merging https://github.com/robwittman/shopify-php-sdk/pull/30, you can access the response headers by accessing the `$lastResponse` object. 

```
$service = new ExampleSerivice($apiInstance);
$res = $service->someMethod($params);
$lastResponse = $service->getLastResponse();
# $lastResponse is instance of GuzzleHttp\Psr7\Response
```

I'll update with new tag when a new version is released

**Comment by robwittman** [comment]
@lyongdee Release `2.3.0` adds `getLastResponse` for getting the raw Guzzle response from a service. This can be used to access any information Guzzle exposes directly
