### ISSUE TITLE
GraphQL Support 

### ISSUE THREAD

**Issue by ShayneP** [robwittman/shopify-php-sdk#26]
Shopify is doubling down on GraphQL, and we'd love to keep recommending shopify-php-sdk.

We're suggesting that libraries add the ability to make GraphQL queries, and since shopify-php-sdk is one of the more popular libraries for PHP, we were hoping you'd be able to add it to your roadmap.

If anyone in the community wants to work on this with me, email me at shayne@shopify.com and I'd love to talk.

**Comment by robwittman** [comment]
@ShayneP Thanks for reaching out! 

I'm currently planning a new major version of this project. Admittedly, my skills are quite a bit better now than when I first started this. 

Let me poke around the GraphQL documentation a bit. But in shot, I would love to get it added to the plan ASAP!

Thanks again!

**Comment by Busfox** [comment]
I took a crack at adding GraphQL calls here: https://github.com/robwittman/shopify-php-sdk/pull/27

It's pretty basic, but can be used as a starting point. 👌 

I omitted any reference to a version in the url, as it looks like versioning isn't supported yet. I created an issue to have versioned calls implemented here: https://github.com/robwittman/shopify-php-sdk/issues/28

**Comment by robwittman** [comment]
@Busfox Sorry for the delay, hard to find time lately. The master branch now supports URLs using Shopify's API Versioning

If you want to pull that in, you can update your GraphQL URL to just use `graphql.json`, and it should work with versioning. I'd be excited to get it merged in, there may be a few projects that can utilize it

**Comment by robwittman** [comment]
Fixed with #40
