### ISSUE TITLE
Add versioning support

### ISSUE THREAD

**Issue by Busfox** [robwittman/shopify-php-sdk#28]
Shopify's Admin APIs are now versioned! 🎉 

Specifying no version in the API is still supported, but that won't always be the case. A version will need to be specified once the `2020-04` version is released, at which point calls using this library will break. Version support should be added before then.

Check out the versioning docs here: https://help.shopify.com/en/api/versioning

**Comment by lyongdee** [comment]
Admins APIs are versioned.

**Comment by robwittman** [comment]
https://github.com/robwittman/shopify-php-sdk/issues/28 has been merged into master, which fixes request paths to add the API versioning. 

I'm doing some badly needed code cleanup and test updates, but I'll probably cut a `3.*` tag sometime in the next few days

**Comment by robwittman** [comment]
I've create release `2.3.0` which contains API versioning
