### ISSUE TITLE
initialize

### ISSUE THREAD

**Issue by BryanYeh** [robwittman/shopify-php-sdk#4]
```
        $options = array(
            'api_key' => 'my-key',
            'api_secret' => 'my-secret',
            'redirect_uri' => "http://localhost/shopify/",
            'permissions' => "read_products",
            'store' => $_GET['shop'],
        );

        \Shopify\Shopify::init($options);

        if(isset($_GET['code']))
        {
            header("Location: ".\Shopify\Auth::authorizationUrl());
        } else {
            echo \Shopify\Auth::accessToken();
        }
```

Why is it that I am getting **Strict API execution requires a nonce for Authentication requests** at the `\Shopify\Auth::accessToken();`

I wrote didn't really change anything with the example you put.

**Comment by robwittman** [comment]
Try adding 
`'strict' => FALSE`
 to the $options array when initializing. The nonce is a security mechanism that ought to be implemented but the library does not support it yet, so it can't be run in 'strict' mode. 

I'll update the documentation as soon as I can

**Comment by BryanYeh** [comment]
I changed it to `FALSE`and I get this problem `curl_error(): 24 is not a valid cURL handle resource in C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\Http\Client.php on line 125`

**Comment by robwittman** [comment]
Ahh, it seems the curl resource is being closed before it can handle the error. This was only happening when curl_exec() failed, due to no network or failure to resolve the host. 

v1.0.3: Http\Client now handles the exception before closing the cURL resource, and I've also added tests for the Client object. 

Now onto the meat of the issue, why is cURL failing to connect / hitting timeout? 

I haven't tested the library on a windows box yet, does phpunit succeed on your system?

**Comment by BryanYeh** [comment]
K, after updating it, it fixed the problem. Then I fixed a bunch of my errors after that. 
Then came to this 406 error from shopify. All I have is below besides a basic php framework I'm using.

```
        $options = array(
            'api_key' => 'my-key',
            'api_secret' => 'my-secret',
            'redirect_uri' => "http://localhost/shopify/",
            'permissions' => "read_products",
            'store' => $_GET['shop'],
        );

        \Shopify\Shopify::init($options);

        if(isset($_GET['code']))
        {
            header("Location: ".\Shopify\Auth::authorizationUrl());
        } else {
            echo \Shopify\Auth::accessToken();
        }
```

-Just a suggestion: add error codes into the message in the `handleHttpCode` function in the `Http\Client.php`

---

This is what I get from phpunit

```
Warning: Declaration of Shopify\FulfillmentEvent::all($order_id, $fulfillment_id) should be compatible with Shopify\AbstractChildObject::all($parentId, $params = Array) in C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\FulfillmentEvent.php on line 82

Warning: Declaration of Shopify\FulfillmentEvent::get($order_id, $fulfillment_id, $event_id) should be compatible with Shopify\AbstractChildObject::get($id, $parentId) in C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\FulfillmentEvent.php on line 82

Warning: Declaration of Shopify\Metafield::all() should be compatible with Shopify\AbstractObject::all($params = Array) in C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\Metafield.php on line 37

Warning: Declaration of Shopify\Metafield::get() should be compatible with Shopify\AbstractObject::get($id = 0) in C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\Metafield.php on line 37
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 248 ( 25%)
.....................................F......................... 126 / 248 ( 50%)
............................................................... 189 / 248 ( 76%)
...........................................................     248 / 248 (100%)

Time: 5.31 seconds, Memory: 6.00MB

There was 1 failure:

1) Shopify\ClientTest::testClientInvalidDomain
Failed asserting that exception of type "Shopify\Exception\CurlException" matches expected exception "\Shopify\Exception\ApiException". Message was: "Could not connect to Shopify (0.0.0.0). Please check your internet connection and try again. If this problem persists, you should check Shopify's service status

(Network error [errno 7]: Failed to connect to 0.0.0.0 port 80: Address not available)" at
C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\Http\Client.php:213
C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\lib\Http\Client.php:126
C:\wamp\www\shopify\vendor\robby-bugatti\shopify-php-sdk\tests\Http\ClientTest.php:20
.

FAILURES!
Tests: 248, Assertions: 217, Failures: 1.
```

**Comment by robwittman** [comment]
First, I had that if statement backwards. It should be
`if( ! isset($_GET['code'])) {` 
As it was written, it was attempting to get an access token, even though an auth code was not present. That is most likely the cause for the 406 you're receiving. Did it redirect you to Shopify to ask for credentials at all? 

Either way, the documentation has been updated, and I've added examples with both strict and non-strict authentication. You can copy those over, fill in with your credentials, and it ought to work. As for the phpunit results, I have yet to figure out why it is throwing a different exception than expected. 

Any chance you could pull down the latest commit, and make sure its working for you?

**Comment by BryanYeh** [comment]
## Strict:

I copied the example code for the strict, but once it reaches `header("Location: " . \Shopify\Auth::authorizationUrl());` I get **Strict API execution requires a nonce for Authentication requests**. 

If I put `\Shopify\Auth::setNonce($nonce);` before  `$storageEngine->store('auth_nonce', $nonce);`, the app installs, but once I try to open the app, the `$accessToken = \Shopify\Auth::accessToken();` I get **Strict API execution requires a nonce for Authentication requests**

## non-strict:

it works perfectly

**Comment by robwittman** [comment]
Are you using the Embedded App SDK?

**Comment by BryanYeh** [comment]
No

**Comment by BryanYeh** [comment]
It works now, the `validateHmac`was missing as mentioned in issue #6 , I just added it in
